apiVersion: v1
kind: Pod
metadata:
  name: netpolicy-test
  labels:
    app: pr-sandbox
spec:
  runtimeClassName: gvisor
  containers:
    - name: test
      image: us-central1-docker.pkg.dev/securepr-505401/pr-sandbox-repo/pr-sandbox:v2
      command: ["sleep", "300"]